remote_theme: "mmistakes/jekyll-theme-basically-basic"
title: LCI Fantasy Football
description: Overview of the league with seasonal stats and league history
logo: /assets/logo.png

twitter_username: TheFifthsWord
github_username:  regsmith
plugins:
  - jekyll-feed

regsmith:
  name: Reg Smith
  twitter: TheFifthsWord
  picture: /assets/authors/regsmith.jpeg

url: http://lcifantasy.ca

gems:
  - jekyll-redirect-from
