remote_theme: "mmistakes/jekyll-theme-basically-basic"
title: League of Calamitous Intent
description: Overview of the league with seasonal stats and league history
logo: /assests/logo.png

twitter_username: TheFifthsWord
github_username:  regsmith
plugins:
  - jekyll-feed
